usr/share/backgrounds/minios6-desert.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-desert-logo.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-jungle.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-jungle-logo.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-sea.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-sea-logo.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-twilight.jpg usr/share/backgrounds
usr/share/backgrounds/minios6-twilight-logo.jpg usr/share/backgrounds
